name: network_image_mock
description: Utility for providing mocked Image.network response in Flutter widget tests.
version: 2.0.1
homepage: https://github.com/stelynx/network_image_mock
repository: https://github.com/stelynx/network_image_mock

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
